export const dataInitial = [
    {
        id: 1,
        name: 'folder1',
        type: 'folder',
        path: [1],
        parentId: false,
        children: true,
    },
    {
        id: 0,
        name: 'file0',
        type: 'file',
        parentId: false,
        path: [0],
        children: false,
        text: '',
    },
    {
        id: 2,
        name: 'file1',
        type: 'file',
        path:[1,2],
        parentId: 1,
        children: false,
        text: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    },
    {
        id: 3,
        name: 'file3',
        type: 'file',
        path:[1,3],
        parentId: 1,
        children: false,
        text: '',
    },
    {
        id: 5,
        name: 'folder5',
        type: 'folder',
        path:[1,5],
        parentId: 1,
        children: true,
    },
    {
        id: 6,
        name: 'file6',
        type: 'file',
        path:[1,5,6],
        parentId: 5,
        text: '',
    },
    {
        id: 7,
        name: 'file7',
        type: 'file',
        path:[1,5,7],
        parentId: 5,
        text: '',
    },
    {
        id: 9,
        name: 'folder9',
        type: 'folder',
        path:[1,5,9],
        parentId: 5,
        children: true,
    },
    {
        id: 10,
        name: 'file10',
        type: 'file',
        path: [1,5,9,10],
        parentId: 9,
        text: '',
    },
    {
        id: 11,
        name: 'folder11',
        type: 'folder',
        path: [1,5,9,11],
        parentId: 9,
        children: false,
    },
]